spring:
  application:
    name: home_choice
  datasource:
    url: jdbc:postgresql://localhost:5432/home_choice
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    aws:
      credentials:
        secret-key:
        access-key:
      region:
        static:

cloud-storage:
    bucket-name:

jwt:
  secret-key:

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true