spring:
  application:
    name: home_choice
  datasource:
    url: jdbc:mysql://localhost:3306/home_choice
    username: root
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    aws:
      credentials:
        secret-key:
        access-key:
      region:
        static: