spring:
  application:
    name: home_choice
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    aws:
      credentials:
        secret-key: ${AWS_SECRET_KEY}
        access-key: ${AWS_ACCESS_KEY}
      region:
        static: ${AWS_REGION}

cloud-storage:
    bucket-name: ${AWS_BUCKET_NAME}

jwt:
  secret-key: ${JWT_SECRET_KEY}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true