spring:
  application:
    name: home_choice
  datasource:
    url: jdbc:postgresql://localhost:5432/home_choice
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

cloud-storage:
  s3:
    bucket-name:
    access-key:
    secret-key:
    region:

jwt:
  secret-key: