spring:
  application:
    name: home_choice
  datasource:
    url: jdbc:postgresql://localhost:5432/home_choice
    username: postgres
    password: 
  jpa:
    database-platform: org.postgresql.Driver
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    aws:
      credentials:
        secret-key:
        access-key:
      region:
        static:
