spring:
  application:
    name: homechoice
  datasource:
    url: jdbc:mysql://localhost:3306/home_choice
    username: root
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: true